language: objective-c  

script : xctool -workspace edXVideoLocker.xcworkspace -scheme edXVideoLockerTests -sdk iphonesimulator build test

branches:
    only:
        - master
notifications:
  email: true
